eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: goods-order
    status-page-url: http://localhost:${server.port}/swagger-ui.html
server:
  port: 8890
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoping?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # redis
    database: 0
    host: 192.168.67.101
    port: 6379
    password: 123456
  application:
    name: goods-order
mybatis:
  typeAliasesPackage: com.brady.order.entity
  mapperLocations: classpath:mapper/*.xml
xxl:
  job:
    accessToken:
    executor:
      appname: goods-order
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 9999
    admin:
      addresses: http://127.0.0.1:8081/xxl-job-admin
