package com.brady.order.entity;

import java.io.Serializable;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.gid
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goods_name
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.price
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.comment
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.username
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.uid
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.tel
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.addr
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.update_time
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.gid
     *
     * @return the value of orders.gid
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.gid
     *
     * @param gid the value for orders.gid
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goods_name
     *
     * @return the value of orders.goods_name
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goods_name
     *
     * @param goodsName the value for orders.goods_name
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.price
     *
     * @return the value of orders.price
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.price
     *
     * @param price the value for orders.price
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.comment
     *
     * @return the value of orders.comment
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.comment
     *
     * @param comment the value for orders.comment
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.username
     *
     * @return the value of orders.username
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.username
     *
     * @param username the value for orders.username
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.uid
     *
     * @return the value of orders.uid
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.uid
     *
     * @param uid the value for orders.uid
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.tel
     *
     * @return the value of orders.tel
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.tel
     *
     * @param tel the value for orders.tel
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.addr
     *
     * @return the value of orders.addr
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.addr
     *
     * @param addr the value for orders.addr
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.update_time
     *
     * @return the value of orders.update_time
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.update_time
     *
     * @param updateTime the value for orders.update_time
     *
     * @mbg.generated Tue Jan 12 15:35:04 CST 2021
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}